// Makes src/components/connect/worldDots.ts: the world as a grid of dots, each
// land dot with the country it falls in, for the Map look of the connection
// card (the exit's country lights up).
//
// Input: Natural Earth 1:50m admin-0 countries, public domain
// (https://www.naturalearthdata.com). Not kept in the repo; download it once:
//
//   curl -L -o ne_50m_countries.geojson \
//     https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
//   node scripts/world-dots.mjs ne_50m_countries.geojson
//
// A cell is land when at least two of five sample points (the centre and four
// quarter points) fall inside a country; it belongs to the country most of
// those points fall in. Countries too small for a cell (Singapore, Malta) still
// get their label point, which is where the card puts its ring.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const STEP = 3; // degrees per cell
const LON0 = -180;
const LAT0 = 84; // the top edge; the bottom edge leaves Antarctica out
const COLS = 360 / STEP;
const ROWS = Math.round((LAT0 - -57) / STEP);

const input = process.argv[2];
if (!input) {
  console.error("usage: node scripts/world-dots.mjs <ne_50m_admin_0_countries.geojson>");
  process.exit(2);
}
const features = JSON.parse(readFileSync(input, "utf8")).features;

/** A plain two-letter code: ISO_A2, or the Natural Earth fallback for the
    places ISO_A2 leaves as -99 or writes differently (France, Norway, Kosovo,
    Taiwan). Somaliland, N. Cyprus and Siachen stay land without a code. */
function codeOf(p) {
  for (const c of [p.ISO_A2, p.ISO_A2_EH]) if (typeof c === "string" && /^[A-Z]{2}$/.test(c)) return c.toLowerCase();
  return null;
}

const shapes = features.map((f) => {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  let minX = 180, minY = 90, maxX = -180, maxY = -90;
  for (const poly of polys)
    for (const ring of poly)
      for (const [x, y] of ring) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
  return { code: codeOf(f.properties), polys, box: [minX, minY, maxX, maxY], label: [f.properties.LABEL_X, f.properties.LABEL_Y] };
});

/** Even-odd ray casting over every ring of a polygon, so holes count out. */
function inPolygon(x, y, poly) {
  let inside = false;
  for (const ring of poly)
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [xi, yi] = ring[i];
      const [xj, yj] = ring[j];
      if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
    }
  return inside;
}

function shapeAt(x, y) {
  for (const s of shapes) {
    const [a, b, c, d] = s.box;
    if (x < a || x > c || y < b || y > d) continue;
    if (s.polys.some((p) => inPolygon(x, y, p))) return s;
  }
  return null;
}

const byCountry = new Map(); // code -> cell numbers
const noCountry = [];
let land = 0;
for (let row = 0; row < ROWS; row++) {
  for (let col = 0; col < COLS; col++) {
    const lon = LON0 + (col + 0.5) * STEP;
    const lat = LAT0 - (row + 0.5) * STEP;
    const q = STEP / 4;
    const hits = [
      [lon, lat],
      [lon - q, lat - q],
      [lon + q, lat - q],
      [lon - q, lat + q],
      [lon + q, lat + q],
    ]
      .map(([x, y]) => shapeAt(x, y))
      .filter(Boolean);
    if (hits.length < 2) continue;
    land++;
    const votes = new Map();
    for (const s of hits) votes.set(s.code, (votes.get(s.code) ?? 0) + 1);
    const code = [...votes.entries()].sort((a, b) => b[1] - a[1])[0][0];
    const cell = row * COLS + col;
    if (code) {
      if (!byCountry.has(code)) byCountry.set(code, []);
      byCountry.get(code).push(cell);
    } else noCountry.push(cell);
  }
}

// Label points in grid units (column, row), one decimal.
const labels = {};
for (const s of shapes) {
  if (!s.code || labels[s.code]) continue;
  const [lon, lat] = s.label;
  if (typeof lon !== "number" || typeof lat !== "number") continue;
  labels[s.code] = [Math.round(((lon - LON0) / STEP) * 10) / 10, Math.round(((LAT0 - lat) / STEP) * 10) / 10];
}

const b36 = (cells) => cells.map((c) => c.toString(36)).join(",");
const codes = [...byCountry.keys()].sort();
const out = `/* The world as dots, for the Map look of the connection card: the exit's
   country lights up. Generated by scripts/world-dots.mjs from Natural Earth
   1:50m admin-0 countries (public domain, naturalearthdata.com). Do not edit
   by hand; run the script again.

   A cell is ${STEP} degrees square; cell number = row * ${COLS} + column, written in
   base 36. Row 0 starts at ${LAT0} degrees north, column 0 at ${LON0} degrees. */

export const GRID = { cols: ${COLS}, rows: ${ROWS} } as const;

/** Land cells per country (lowercase ISO 3166-1 code). */
export const COUNTRY_CELLS: Readonly<Record<string, string>> = {
${codes.map((c) => `  ${c}: "${b36(byCountry.get(c))}",`).join("\n")}
};

/** Land that belongs to no code of its own (Somaliland, N. Cyprus, Siachen). */
export const OTHER_LAND = "${b36(noCountry)}";

/** Where each country's name sits, in cells: [column, row]. The card's ring
    goes here, so a country too small for a dot of its own still shows. */
export const LABELS: Readonly<Record<string, readonly [number, number]>> = {
${Object.keys(labels)
  .sort()
  .map((c) => `  ${c}: [${labels[c][0]}, ${labels[c][1]}],`)
  .join("\n")}
};
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "components", "connect", "worldDots.ts");
writeFileSync(target, out);
console.log(`${land} land cells, ${codes.length} countries with cells, ${Object.keys(labels).length} label points -> ${target}`);
