// Writes src/windows_zones.rs: every IANA time zone ("America/Chicago") to the Windows zone
// that keeps the same time ("Central Standard Time"), from Unicode CLDR's windowsZones.xml,
// the table Windows and ICU use themselves.
//
//   node scripts/windows-zones.mjs [path-to-windowsZones.xml]
//   (without a path it downloads the current file from the CLDR repository)
//
// CLDR still writes a few zones under their old names (Asia/Calcutta, Europe/Kiev); the IP
// API answers with today's (Asia/Kolkata, Europe/Kyiv). RENAMED adds today's name next to
// every old one CLDR uses, from the IANA database's `backward` file.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const SOURCE = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml";
const OUT = path.join(import.meta.dirname, "..", "src", "windows_zones.rs");

/* Today's name for each old name CLDR still uses (IANA `backward`). */
const RENAMED = {
  "Asia/Calcutta": "Asia/Kolkata",
  "Europe/Kiev": "Europe/Kyiv",
  "Asia/Katmandu": "Asia/Kathmandu",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Saigon": "Asia/Ho_Chi_Minh",
  "America/Godthab": "America/Nuuk",
  "Atlantic/Faeroe": "Atlantic/Faroe",
  "Pacific/Truk": "Pacific/Chuuk",
  "Pacific/Ponape": "Pacific/Pohnpei",
  "Pacific/Enderbury": "Pacific/Kanton",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "America/Catamarca": "America/Argentina/Catamarca",
  "America/Cordoba": "America/Argentina/Cordoba",
  "America/Jujuy": "America/Argentina/Jujuy",
  "America/Mendoza": "America/Argentina/Mendoza",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "America/Louisville": "America/Kentucky/Louisville",
  "Asia/Dacca": "Asia/Dhaka",
  "Asia/Thimbu": "Asia/Thimphu",
  "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
  "Asia/Macao": "Asia/Macau",
  "Asia/Ujung_Pandang": "Asia/Makassar",
  "Africa/Asmera": "Africa/Asmara",
  "Europe/Belfast": "Europe/London",
  "America/Coral_Harbour": "America/Atikokan",
};

const xml = process.argv[2] ? readFileSync(process.argv[2], "utf8") : await (await fetch(SOURCE)).text();
const version = xml.match(/<mapTimezones[^>]*typeVersion="([^"]+)"/)?.[1] ?? "unknown";

const map = new Map();
const add = (iana, windows) => {
  if (iana && !map.has(iana)) map.set(iana, windows);
};
// The "001" line is each Windows zone's main place; it goes in first, then every other
// place listed under the zone, then today's names of the renamed ones.
const lines = [...xml.matchAll(/<mapZone other="([^"]+)" territory="([^"]+)" type="([^"]+)"\s*\/>/g)];
for (const [, windows, territory, types] of lines) if (territory === "001") add(types.split(" ")[0], windows);
for (const [, windows, , types] of lines) for (const t of types.split(" ")) add(t, windows);
for (const [old, today] of Object.entries(RENAMED)) if (map.has(old)) add(today, map.get(old));
map.delete("Etc/Unknown");

const rows = [...map].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
const rust = `//! IANA time zone to Windows time zone, for matching the computer's clock to the exit
//! (timezone.rs). Generated by scripts/windows-zones.mjs from Unicode CLDR's
//! windowsZones.xml (typeVersion ${version}); run it again to update, never edit by hand.

/// Sorted by the IANA name, for a binary search.
pub(crate) const WINDOWS_ZONES: &[(&str, &str)] = &[
${rows.map(([iana, win]) => `    (${JSON.stringify(iana)}, ${JSON.stringify(win)}),`).join("\n")}
];
`;
writeFileSync(OUT, rust);
console.log(`windows_zones.rs: ${rows.length} zones, CLDR typeVersion ${version}`);
